// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: add_user.sql

package db

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (username, email, hashed_password)
VALUES ($1, $2, $3)
RETURNING  username, email, created_at
`

type AddUserParams struct {
	Username       string
	Email          string
	HashedPassword string
}

type AddUserRow struct {
	Username  string
	Email     string
	CreatedAt sql.NullTime
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (AddUserRow, error) {
	row := q.db.QueryRowContext(ctx, addUser, arg.Username, arg.Email, arg.HashedPassword)
	var i AddUserRow
	err := row.Scan(&i.Username, &i.Email, &i.CreatedAt)
	return i, err
}
