// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: add_room.sql

package db

import (
	"context"
)

const addRoom = `-- name: AddRoom :exec
    INSERT INTO rooms (name, user_id, index)
    VALUES ($1,
     (SELECT ID  FROM users WHERE username = $2),
      COALESCE((SELECT MAX(index)  FROM rooms WHERE rooms.user_id = user_id),0)+1)
`

type AddRoomParams struct {
	Name     string
	Username string
}

func (q *Queries) AddRoom(ctx context.Context, arg AddRoomParams) error {
	_, err := q.db.ExecContext(ctx, addRoom, arg.Name, arg.Username)
	return err
}
