// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: check_email_exists.sql

package db

import (
	"context"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email = $1
) AS exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
