// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: check_device_exists.sql

package db

import (
	"context"
)

const checkDeviceExists = `-- name: CheckDeviceExists :one

SELECT sensors.id, 'sensor' as device_type
FROM sensors 
WHERE sensors.id = $1
UNION ALL
SELECT cameras.id, 'camera' as device_type
FROM cameras 
WHERE cameras.id = $1
UNION ALL
SELECT switches.id, 'switch' as device_type
FROM switches 
WHERE switches.id = $1
LIMIT 1
`

type CheckDeviceExistsRow struct {
	ID         int32
	DeviceType string
}

func (q *Queries) CheckDeviceExists(ctx context.Context, id int32) (CheckDeviceExistsRow, error) {
	row := q.db.QueryRowContext(ctx, checkDeviceExists, id)
	var i CheckDeviceExistsRow
	err := row.Scan(&i.ID, &i.DeviceType)
	return i, err
}
