// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_email.sql

package db

import (
	"context"
)

const getEmail = `-- name: GetEmail :one
SELECT email
FROM users
WHERE username = $1
`

func (q *Queries) GetEmail(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEmail, username)
	var email string
	err := row.Scan(&email)
	return email, err
}
