// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_sensors_by_room.sql

package db

import (
	"context"
)

const getsensorsByRoom = `-- name: GetsensorsByRoom :many
SELECT id, name, color, type_id as type, value ,index
FROM sensors
WHERE room_id = $1
`

type GetsensorsByRoomRow struct {
	ID    int32
	Name  string
	Color int64
	Type  int32
	Value int32
	Index int32
}

func (q *Queries) GetsensorsByRoom(ctx context.Context, roomID int32) ([]GetsensorsByRoomRow, error) {
	rows, err := q.db.QueryContext(ctx, getsensorsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetsensorsByRoomRow
	for rows.Next() {
		var i GetsensorsByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Type,
			&i.Value,
			&i.Index,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
