// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_user_credentials.sql

package db

import (
	"context"
)

const getUserCredentials = `-- name: GetUserCredentials :one
SELECT username, hashed_password
FROM users
WHERE username = $1
`

type GetUserCredentialsRow struct {
	Username       string
	HashedPassword string
}

func (q *Queries) GetUserCredentials(ctx context.Context, username string) (GetUserCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCredentials, username)
	var i GetUserCredentialsRow
	err := row.Scan(&i.Username, &i.HashedPassword)
	return i, err
}
