// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_switch_state.sql

package db

import (
	"context"
	"database/sql"
)

const getSwitchState = `-- name: GetSwitchState :one
SELECT value as state
FROM switches
WHERE id = $1 and token = $2
`

type GetSwitchStateParams struct {
	ID    int32
	Token sql.NullString
}

func (q *Queries) GetSwitchState(ctx context.Context, arg GetSwitchStateParams) (int16, error) {
	row := q.db.QueryRowContext(ctx, getSwitchState, arg.ID, arg.Token)
	var state int16
	err := row.Scan(&state)
	return state, err
}
