// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: link_camera.sql

package db

import (
	"context"
	"database/sql"
)

const linkCamera = `-- name: LinkCamera :one
UPDATE cameras
SET name = $1, color = $2, room_id = $3, index = (COALESCE((SELECT MAX(index) FROM cameras WHERE cameras.room_id = $3), 0) + 1)
WHERE cameras.id = $4 AND cameras.token = $5
RETURNING cameras.id
`

type LinkCameraParams struct {
	Name   string
	Color  int64
	RoomID int32
	ID     int32
	Token  sql.NullString
}

func (q *Queries) LinkCamera(ctx context.Context, arg LinkCameraParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, linkCamera,
		arg.Name,
		arg.Color,
		arg.RoomID,
		arg.ID,
		arg.Token,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
