// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: link_sensor.sql

package db

import (
	"context"
	"database/sql"
)

const linkSensor = `-- name: LinkSensor :one
UPDATE sensors
SET name = $1, color = $2, room_id = $3, index = (COALESCE((SELECT MAX(index) FROM sensors WHERE sensors.room_id = $3), 0) + 1)
WHERE sensors.id = $4 AND sensors.token = $5
RETURNING sensors.id
`

type LinkSensorParams struct {
	Name   string
	Color  int64
	RoomID int32
	ID     int32
	Token  sql.NullString
}

func (q *Queries) LinkSensor(ctx context.Context, arg LinkSensorParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, linkSensor,
		arg.Name,
		arg.Color,
		arg.RoomID,
		arg.ID,
		arg.Token,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
