// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type ApiAuthentication struct {
	AuthID     int32
	UserID     int32
	ApiKey     string
	DeviceName string
	CreatedAt  sql.NullTime
	ExpiresAt  sql.NullTime
}

type Camera struct {
	ID     int32
	Name   string
	RoomID int32
	Value  string
	Color  int64
	Index  int32
	Token  sql.NullString
}

type CameraCommand struct {
	CommandID   int32
	CameraID    int32
	CommandName string
	Description string
}

type CameraCommandLog struct {
	LogID     int32
	CameraID  int32
	CommandID int32
	Timestamp sql.NullTime
}

type CameraSnap struct {
	SnapID    int32
	CameraID  int32
	ImageUrl  string
	Timestamp sql.NullTime
}

type GeneralCommand struct {
	CommandID   int32
	CommandName string
	Description string
}

type GeneralCommandLog struct {
	LogID            int32
	CommandID        int32
	ExecutedByUserID int32
	Timestamp        sql.NullTime
}

type Room struct {
	ID     int32
	Name   string
	UserID int32
	Index  int32
}

type Sensor struct {
	ID     int32
	Type   string
	Name   string
	RoomID int32
	TypeID int32
	Value  int32
	Index  int32
	Color  int64
	Token  sql.NullString
}

type SensorCommand struct {
	CommandID   int32
	SensorID    int32
	CommandName string
	Description string
}

type SensorCommandLog struct {
	LogID     int32
	SensorID  int32
	CommandID int32
	Timestamp sql.NullTime
}

type SensorLog struct {
	LogID     int32
	SensorID  int32
	Reading   float64
	Timestamp sql.NullTime
}

type SensorType struct {
	TypeID      int32
	TypeName    string
	Description string
}

type Switch struct {
	ID         int32
	Name       string
	RoomID     int32
	Color      int64
	IconCode   int32
	IconFamily string
	Index      int32
	Type       int32
	Value      int16
	Token      sql.NullString
}

type SwitchCommand struct {
	CommandID   int32
	SwitchID    int32
	CommandName string
	Description string
}

type SwitchCommandLog struct {
	LogID     int32
	SwitchID  int32
	CommandID int32
	Timestamp sql.NullTime
}

type SwitchLog struct {
	LogID     int32
	SwitchID  int32
	State     bool
	Timestamp sql.NullTime
}

type SwitchesSchedule struct {
	ScheduleID         int32
	SwitchID           int32
	CommandID          int32
	ScheduledTime      time.Time
	IsRecurring        sql.NullBool
	RecurrenceInterval sql.NullInt64
}

type User struct {
	ID             int32
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
