// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_room_index.sql

package db

import (
	"context"
)

const setRoomIndex = `-- name: SetRoomIndex :exec
UPDATE rooms
SET index = $1
WHERE rooms.id = $2 
  AND user_id IN (
    SELECT users.id 
    FROM users 
    WHERE users.username = $3
  )
`

type SetRoomIndexParams struct {
	Index    int32
	ID       int32
	Username string
}

func (q *Queries) SetRoomIndex(ctx context.Context, arg SetRoomIndexParams) error {
	_, err := q.db.ExecContext(ctx, setRoomIndex, arg.Index, arg.ID, arg.Username)
	return err
}
