// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_switch_index.sql

package db

import (
	"context"
)

const setSwitchIndex = `-- name: SetSwitchIndex :exec
update switches
set index = $1
where id = $2
`

type SetSwitchIndexParams struct {
	Index int32
	ID    int32
}

func (q *Queries) SetSwitchIndex(ctx context.Context, arg SetSwitchIndexParams) error {
	_, err := q.db.ExecContext(ctx, setSwitchIndex, arg.Index, arg.ID)
	return err
}
