// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_sensor_value.sql

package db

import (
	"context"
	"database/sql"
)

const setSensorValue = `-- name: SetSensorValue :exec
UPDATE sensors
SET value = $1
WHERE id = $2 and token = $3
`

type SetSensorValueParams struct {
	Value int32
	ID    int32
	Token sql.NullString
}

func (q *Queries) SetSensorValue(ctx context.Context, arg SetSensorValueParams) error {
	_, err := q.db.ExecContext(ctx, setSensorValue, arg.Value, arg.ID, arg.Token)
	return err
}
