// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_sensor_index.sql

package db

import (
	"context"
)

const setSensorIndex = `-- name: SetSensorIndex :exec
UPDATE sensors
SET index = $1
WHERE sensors.id = $2 
  AND room_id IN  (
    SELECT rooms.id 
    FROM rooms 
    WHERE rooms.user_id  IN  (
            SELECT users.id 
            FROM users 
            WHERE users.username = $3
        )
  )
`

type SetSensorIndexParams struct {
	Index    int32
	ID       int32
	Username string
}

func (q *Queries) SetSensorIndex(ctx context.Context, arg SetSensorIndexParams) error {
	_, err := q.db.ExecContext(ctx, setSensorIndex, arg.Index, arg.ID, arg.Username)
	return err
}
