// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_switch_value.sql

package db

import (
	"context"
)

const setSwitchValue = `-- name: SetSwitchValue :exec
UPDATE switches
SET value = $1
WHERE switches.id = $2 
  AND room_id IN  (
    SELECT rooms.id 
    FROM rooms 
    WHERE rooms.user_id  IN  (
            SELECT users.id 
            FROM users 
            WHERE users.username = $3
        )
  )
`

type SetSwitchValueParams struct {
	Value    int16
	ID       int32
	Username string
}

func (q *Queries) SetSwitchValue(ctx context.Context, arg SetSwitchValueParams) error {
	_, err := q.db.ExecContext(ctx, setSwitchValue, arg.Value, arg.ID, arg.Username)
	return err
}
