// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_sensor_index.sql

package db

import (
	"context"
)

const setSensorIndex = `-- name: SetSensorIndex :exec
update sensors
set index = $1
where id = $2
`

type SetSensorIndexParams struct {
	Index int32
	ID    int32
}

func (q *Queries) SetSensorIndex(ctx context.Context, arg SetSensorIndexParams) error {
	_, err := q.db.ExecContext(ctx, setSensorIndex, arg.Index, arg.ID)
	return err
}
