// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_camera_index.sql

package db

import (
	"context"
)

const setCameraIndex = `-- name: SetCameraIndex :exec
update cameras
set index = $1
where id = $2
`

type SetCameraIndexParams struct {
	Index int32
	ID    int32
}

func (q *Queries) SetCameraIndex(ctx context.Context, arg SetCameraIndexParams) error {
	_, err := q.db.ExecContext(ctx, setCameraIndex, arg.Index, arg.ID)
	return err
}
