// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_room_index.sql

package db

import (
	"context"
)

const setRoomIndex = `-- name: SetRoomIndex :exec
update rooms
set index = $1
where id = $2
`

type SetRoomIndexParams struct {
	Index int32
	ID    int32
}

func (q *Queries) SetRoomIndex(ctx context.Context, arg SetRoomIndexParams) error {
	_, err := q.db.ExecContext(ctx, setRoomIndex, arg.Index, arg.ID)
	return err
}
