// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_switch_index.sql

package db

import (
	"context"
)

const setSwitchIndex = `-- name: SetSwitchIndex :exec
UPDATE switches
SET index = $1
WHERE switches.id = $2 
  AND room_id IN  (
    SELECT rooms.id 
    FROM rooms 
    WHERE rooms.user_id  IN  (
            SELECT users.id 
            FROM users 
            WHERE users.username = $3
        )
  )
`

type SetSwitchIndexParams struct {
	Index    int32
	ID       int32
	Username string
}

func (q *Queries) SetSwitchIndex(ctx context.Context, arg SetSwitchIndexParams) error {
	_, err := q.db.ExecContext(ctx, setSwitchIndex, arg.Index, arg.ID, arg.Username)
	return err
}
