// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_camera_index.sql

package db

import (
	"context"
)

const setCameraIndex = `-- name: SetCameraIndex :exec
UPDATE cameras
SET index = $1
WHERE cameras.id = $2 
  AND room_id IN  (
    SELECT rooms.id 
    FROM rooms 
    WHERE rooms.user_id  IN  (
            SELECT users.id 
            FROM users 
            WHERE users.username = $3
        )
  )
`

type SetCameraIndexParams struct {
	Index    int32
	ID       int32
	Username string
}

func (q *Queries) SetCameraIndex(ctx context.Context, arg SetCameraIndexParams) error {
	_, err := q.db.ExecContext(ctx, setCameraIndex, arg.Index, arg.ID, arg.Username)
	return err
}
