// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: validate_credentials.sql

package db

import (
	"context"
)

const validateCredentials = `-- name: ValidateCredentials :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1 AND hashed_password = $2)
`

type ValidateCredentialsParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) ValidateCredentials(ctx context.Context, arg ValidateCredentialsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, validateCredentials, arg.Username, arg.HashedPassword)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
